### ISSUE TITLE
User can search their entries

### ISSUE THREAD

**Issue by alicejeeunlee** [alicejeeunlee/code-journal#9]
## 📐 Plan

Provide a search box that causes the entries list to only show matches.

## ✅ Task List

- [x] Add `<input type="search">` in HTML
- [x] Ensure search box shows only on `data.view = 'entries'`
- [x] Define a function that compares input value to `title` and `notes`
- [x] Ensure all comparison values have same casing (all lower)
- [x] Loop through all `<li>` entries
  - [x] If the entry's text content includes input
    - [x] Show DOM entries by changing class name
  - [x] Else
    - [x] Hide entries
- [x] Define a function to show all entries
- [x] Apply showAllEntries where applicable
